#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

shellArgument="${1,,}"
case "$shellArgument" in
	"-h" | "--help")
		cat "$DIR/README.md"
		exit 1
		;;
	*)
		;;
esac

# Starts the process in a detached screen so it can be monitored
# Screen closes when done
screen -dmS Xfer "$DIR/data/GetFiles.sh"
